default: &default
  adapter: postgresql
  encoding: unicode
  host: <%= ENV.fetch("TEA-SUBSCRIPTION_DATABASE_HOSTNAME") { "localhost" } %>
  username: <%= ENV.fetch("TEA-SUBSCRIPTION_DATABASE_USERNAME") { "" } %>  
  password: <%= ENV['TEA-SUBSCRIPTION_DATABASE_PASSWORD'] %>
  # For details on connection pooling, see Rails configuration guide
  # https://guides.rubyonrails.org/configuring.html#database-pooling
  pool: 5
development:
  <<: *default
  database: tea_subscription_development
test:
  <<: *default
  database: tea_subscription_test